name: python-tests
on: [push, pull_request]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install python dependencies
        run: pip install -r requirements.txt
      - name: install cdk
        run: npm install -g aws-cdk
      - name: smoke-tests
        run: |
          cp cdk.context.template cdk.context.json
          echo synth test with PKCE and Private Key JWT
          cdk synth
          echo synth test with only Private Key JWT
          sed -i 's/\"pkce\": false/\"pkce\": true/g' cdk.context.json
          cdk synth
