name: python-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: dependencies
        run: pip install -r requirements.txt
      - name: node
        run: node --version
      - name: cdk
        run: cdk --version
